AllCops:
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
